# Миграции стоит называть осознанно(не xxxx_auto....), иначе в разросшихся миграциях будет непонятно, что и где было- будут сплошные авто-миграции. Если меняется нейминг миграций, уже примененных на БД, надо будет быть аккуратным- порядок миграций хранится в таблице (django_migrations) + в самих миграциях есть в зависимость на предыдущей миграции. Хорошая практика- 1 миграция на одну наработку.
# https://nextlinklabs.com/insights/naming-django-migrations-improving-projects 
# Generated by Django 2.2.9 on 2023-02-28 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.Group'),
        ),
    ]
